

#debug: true

spring:
  cache:
    cache-names: outLimit
#    caffeine:
#      spec: initialCapacity=50,maximumSize=500,expireAfterWrite=5s,refreshAfterWrite=7s
    type: caffeine

caffeine:
  spec: initialCapacity=50,maximumSize=500,expireAfterWrite=5s

dynamic:
  default-db: master