

#debug: true

spring:
  cache:
    cache-names: outLimit
#    caffeine:
#      spec: initialCapacity=50,maximumSize=500,expireAfterWrite=50s,refreshAfterWrite=5s
    type: caffeine

caffeine:
  spec: initialCapacity=50,maximumSize=500,expireAfterWrite=50s